### ISSUE TITLE
Add the title of the gallery

### ISSUE THREAD

**Issue by zorodimanche** [modus75/piwigo-modus#8]

**Comment by modus75** [comment]
Where?

**Comment by zorodimanche** [comment]
In the menu bar on the left

**Comment by modus75** [comment]
I don't understand where you want to add it. The menubar is horizontal on large screens and vertical on small screens. There is no space for a variable length title.

The gallery title is shown only on the home page. As soon as we navigate it is replaced with "Home" so that it does not take too much space

**Comment by zorodimanche** [comment]
Then it would be necessary to add a function that always displays the navigation bar because on the page of the images it is deactivated. And add the title of the gallery to the left in the menu (just to the left of "Album")
Then the title of the gallery does not take up much space as it usually makes 5-6-7 letters
